### ISSUE TITLE
RSpace Feedback

### ISSUE THREAD

**Issue by roaldarbol** [rspace-os/rspace-client-python#19]
Hey! I know this will be in the wrong place - but I simply can't find a good channel for supplying feedback on everything RSpace, which is a pity as I'm sure the community would be happy to provide it to improve RSpace. 
Whether it would be a Discussions of a GH repo, a subreddit or Discourse, the open interaction with the community would be great. Ideally accompanied by an approximate roadmap (e.g. see [Obsidian](https://trello.com/b/Psqfqp7I/obsidian-roadmap) or [ProtonMail](https://protonmail.com/blog/engineering-team-2021-update/) for inspiration) for improved transparency. Anyhow, here's a bit of feedback. And if there's an appropriate channel for feedback, just let me know then I'll go there instead.

**Protocols.io integration**. Currently you're able to import/link to protocols, however it's not possible for a completed run record - a feature that seems to fit right into a lab notebook.

**Automatic naming of notebook entries**. Traditionally, we make one entry/page per day as that's the easiest thing to categorise. So a great feature would be an option of automatically creating an entry with the name of the date if there's no entries on that date (i.e. max. 1 automatic entry per day).

**Missing integrations**. On the website it's been saying *Coming soon* or *In development* for quite a few integrations. It would be awesome to know what the ETA is one those, and how they are prioritised. Also, I would highly recommend getting Zenodo on the list. 

Again, I hope this finds its rightful place. And thank you for the work being put in, I appreciate that there must be tons of things to work on. Cheers.

**Comment by richarda23** [comment]
Hi Mikkel
 Thanks for the feedback! True, we don't have a dedicated feedback channel other than contacting support@researchspace.com or via the in-app chat. I've passed your message onto our support team as the issues seem related to RSpace itself rather than this specific python rspace-client project.
 
Just curious, are you using this library or the RSpace API at all? We are trying to make it easier for data scientists / bioinformaticians to interact with RSpace so any suggestions are very welcome.

Thanks again for taking the time to write. 
Best wishes 
 Richard Adams

**Comment by roaldarbol** [comment]
Hi Richard,
Thanks for passing my feedback on. I still haven't used the Python API, but I could imagine using it in the future. I'll get back to you if I come across something. 
Thanks again!
Cheers
Mikkel
