### ISSUE TITLE
Wrapper for Inventory API

### ISSUE THREAD

**Issue by richarda23** [rspace-os/rspace-client-python#9]
The RSpace inventory API is quite complex as it supports the user interface. Some basic facade methods to browse, create and edit samples would be much easier to work with programmatically - particularly PUT requests,
We also want to support easy migration from existing Inventory solutions beyond the simple CSV upload.

May need to refactor to support 2 client modules? Or a class structure ? or keep existing rspace_client and  delegate internally to ELN or Inventory modules? @noreferences  any high-level design ideas appreciated. If we establish this we can add in new methods to support API endpoints incrementally.

**Comment by noreferences** [comment]
User - programmer who uses the `rspace_client` library.

First of all, I think that the user should have to interact through two separate clients when interacting with both Inventory and ELN for making things explicit. Let's imagine the scenario where the `rspace_client` exposes the aggregate of ELN and Inventory methods, but delegates internally. Inventory has an endpoint `/search`, so let's say we add this to the aggregate. It is not immediately clear to the user what they are searching for and need to take extra steps. For contrast, if say we have `eln_client` and `inventory_client`, we add a `search` method to inventory_client it is less ambiguous what is being searched.

Another few reasons why I think separating ELN and Inventory clients is a good idea:
- ELN and Inventory API docs are separated and ELN and Inventory feel like separate products from RSpace user perspective. Hence separation would be more coherent.
- Companies that have many APIs separate out the clients.

  For example AWS Python client `boto3` creates clients in the following way:
  ```python
  session.get_client("s3");
  session.get_client("ec2");
  ```
  I'm not a massive fan of specifying targets as strings because that provides a bad IDE experience.
  
  GCP on the other hand, provide a separate Python package per service they provide.
  
  While these big cloud providers are not an exact comparison to us, as they provide 10s-100s of different services,
  I still think they are good examples to have a look at.

I think the following directory structure would be the most ideal
```
rspace
  eln
    __main__.py  # contains `client = ELNClient`, usecase will be shown in the upcoming paragraph
    eln_client.py
    ...  # any other supporting code
  inventory
    __main__.py  # contains `client = InventoryClient`, usecase will be shown in the upcoming paragraph
    inventory_client.py
    ...  # any other supporting code
  exceptions.py 
  utils
    ...  # Anything shared between eln_client and inv_client, but that the user is unlikely to want
```

This will provide a nice structure for development and a nice interface for the user to do the following:
```python
from rspace import eln, inventory

eln_client = eln.client()
inv_client = inventory.client()
```

or 

```python
import rspace

eln = rspace.eln.client()
inventory = rspace.inventory.client()

# random example
results = inventory.search(query="...")
```

exception handling would look something like

```python
import rspace

try:
    ....
except rspace.exceptions.BadRequest as e:
    print(e)
```

**Comment by richarda23** [comment]
That all sounds great. Having two client modules would make it cleaner to code and to use. Configuration (e.g. setting URL and  API token, or reading from environment property or keychain  ) could be used in the same way for both. Also getting the correct client from a method call rather than a string seems more reliable, there are unlikely to be any more than 2 services

**Comment by richarda23** [comment]
Work on this is going on in version-2 branch.

**Comment by richarda23** [comment]
the redesign is now complete in version 2.0+
